
import React,{useEffect,useState} from "react";
import {adminFetch} from "./api";
export default function Products(){
 const [rows,setRows]=useState([]),[cats,setCats]=useState([]),[edit,setEdit]=useState(null),[q,setQ]=useState("");
 const blank={CategoryId:"",Name:"",Description:"",Weight:"250g",Price:"",StockQuantity:0,ImageUrl:"",IsActive:true};
 const load=()=>Promise.all([adminFetch("/products"),adminFetch("/categories")]).then(([p,c])=>{setRows(p.data||[]);setCats(c.data||[])});
 useEffect(()=>{load().catch(console.error)},[]);
 const save=async e=>{e.preventDefault();const body={...edit,CategoryId:Number(edit.CategoryId),Price:Number(edit.Price),StockQuantity:Number(edit.StockQuantity)};await adminFetch(edit.Id?`/products/${edit.Id}`:"/products",{method:edit.Id?"PUT":"POST",body:JSON.stringify(body)});setEdit(null);load()};
 const filtered=rows.filter(x=>`${x.Name} ${x.CategoryName} ${x.Weight}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="admin-content"><h1 className="admin-title">Products</h1><p className="admin-subtitle">Manage names, prices, stock and images without redeploying.</p>
 <div className="admin-toolbar"><input className="admin-input" placeholder="Search products..." value={q} onChange={e=>setQ(e.target.value)}/><button className="admin-btn" onClick={()=>setEdit({...blank})}>+ Add Product</button></div>
 {edit&&<form className="admin-form" onSubmit={save}><div className="admin-field"><label>Product Name</label><input className="admin-input" value={edit.Name} required onChange={e=>setEdit({...edit,Name:e.target.value})}/></div><div className="admin-field"><label>Category</label><select className="admin-select" value={edit.CategoryId} required onChange={e=>setEdit({...edit,CategoryId:e.target.value})}><option value="">Select</option>{cats.map(c=><option key={c.Id} value={c.Id}>{c.Name}</option>)}</select></div><div className="admin-field"><label>Weight</label><input className="admin-input" value={edit.Weight} required onChange={e=>setEdit({...edit,Weight:e.target.value})}/></div><div className="admin-field"><label>Price</label><input type="number" className="admin-input" value={edit.Price} required onChange={e=>setEdit({...edit,Price:e.target.value})}/></div><div className="admin-field"><label>Stock</label><input type="number" className="admin-input" value={edit.StockQuantity} onChange={e=>setEdit({...edit,StockQuantity:e.target.value})}/></div><div className="admin-field"><label>Image URL</label><input className="admin-input" value={edit.ImageUrl||""} placeholder="https://..." onChange={e=>setEdit({...edit,ImageUrl:e.target.value})}/></div><div className="admin-field full"><label>Description</label><textarea className="admin-input" rows="4" value={edit.Description||""} onChange={e=>setEdit({...edit,Description:e.target.value})}/></div><div className="admin-actions full"><button className="admin-btn">Save Product</button><button type="button" className="admin-btn secondary" onClick={()=>setEdit(null)}>Cancel</button></div></form>}
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Image</th><th>Product</th><th>Category</th><th>Weight</th><th>Price</th><th>Stock</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.Id}><td>{x.ImageUrl?<img className="admin-thumb" src={x.ImageUrl} alt=""/>:"—"}</td><td><strong>{x.Name}</strong></td><td>{x.CategoryName}</td><td>{x.Weight}</td><td>₹{Number(x.Price).toLocaleString("en-IN")}</td><td>{x.StockQuantity}</td><td>{x.IsActive?"Active":"Off"}</td><td><button className="admin-btn secondary" onClick={()=>setEdit({...x})}>Edit</button></td></tr>)}</tbody></table></div>
 </div>
}
